# Netlify Build Configuration
[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in Netlify dashboard)
# NEXT_PUBLIC_APP_URL
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
