# Netlify Configuration for Next.js 15
[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

# Next.js Runtime
[build.environment]
  NEXT_PRIVATE_TARGET = "server"

# Functions for Next.js API routes and SSR
[functions]
  directory = "frontend/.netlify/functions"
  node_bundler = "esbuild"

# Essential Next.js Plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (set these in Netlify dashboard):
# NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your_project_id
