// Mock data for development and testing
import { Advertisement, User, Order, Review } from "./types";

export const mockUsers: User[] = [
  {
    id: "user_1",
    address: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb",
    name: "FarmersUnion_TH",
    avatar: undefined,
    joinedDate: "2024-01-15",
    verified: true,
    stats: {
      totalOrders: 234,
      completionRate: 98.5,
      avgShippingTime: 36,
      totalStaked: 5000,
      rating: 4.9,
      reviewCount: 189,
    },
  },
  {
    id: "user_2",
    address: "0x8ba1f109551bD432803012645Ac136ddd64DBA72",
    name: "ElectronicsPro",
    avatar: undefined,
    joinedDate: "2024-03-20",
    verified: true,
    stats: {
      totalOrders: 156,
      completionRate: 96.2,
      avgShippingTime: 48,
      totalStaked: 3000,
      rating: 4.7,
      reviewCount: 134,
    },
  },
  {
    id: "user_3",
    address: "0x5A0b54D5dc17e0AadC383d2db43B0a0D3E029c4c",
    name: "OrganicChicken_VN",
    avatar: undefined,
    joinedDate: "2024-02-10",
    verified: true,
    stats: {
      totalOrders: 89,
      completionRate: 99.1,
      avgShippingTime: 24,
      totalStaked: 2500,
      rating: 4.95,
      reviewCount: 76,
    },
  },
  {
    id: "user_4",
    address: "0x3E5e9111Ae8eB78Fe1CC3bb8915d5D461F3Ef9A9",
    name: "TextileMart_IN",
    avatar: undefined,
    joinedDate: "2024-04-05",
    verified: false,
    stats: {
      totalOrders: 45,
      completionRate: 93.3,
      avgShippingTime: 72,
      totalStaked: 1000,
      rating: 4.5,
      reviewCount: 38,
    },
  },
];

export const mockAdvertisements: Advertisement[] = [
  {
    id: "ad_1",
    seller: mockUsers[0],
    industry: "Agriculture",
    product: "Premium Jasmine Rice",
    description: "Grade A Thai Jasmine rice, directly from our farm. Perfect fragrance and texture. Certified organic.",
    price: 2.5,
    priceUnit: "kg",
    minOrder: 100,
    maxOrder: 5000,
    availableStock: 10000,
    paymentMethods: ["Bank Transfer", "USDT (TRC-20)", "Cash on Delivery"],
    shippingTime: "24-48 hours",
    location: "Bangkok, Thailand",
    terms: "Ship within 48hrs of payment confirmation. Bulk discounts available over 1000kg.",
    images: ["/placeholder-rice.jpg"],
    createdAt: "2024-10-15T08:30:00Z",
    active: true,
  },
  {
    id: "ad_2",
    seller: mockUsers[1],
    industry: "Electronics",
    product: "Unlocked Smartphones - Latest Models",
    description: "Brand new, factory unlocked smartphones. All major brands available. Full warranty included.",
    price: 299,
    priceUnit: "piece",
    minOrder: 1,
    maxOrder: 50,
    availableStock: 200,
    paymentMethods: ["Bank Transfer", "PayPal", "Crypto (USDC)"],
    shippingTime: "3-5 business days",
    location: "Singapore",
    terms: "30-day warranty. International shipping available. Returns accepted within 7 days.",
    images: ["/placeholder-phone.jpg"],
    createdAt: "2024-10-16T14:20:00Z",
    active: true,
  },
  {
    id: "ad_3",
    seller: mockUsers[2],
    industry: "Livestock",
    product: "Free-Range Organic Eggs",
    description: "Farm-fresh eggs from free-range chickens. No antibiotics, organic feed only. Delivered daily.",
    price: 0.35,
    priceUnit: "piece",
    minOrder: 30,
    maxOrder: 500,
    availableStock: 2000,
    paymentMethods: ["Bank Transfer", "Cash on Delivery"],
    shippingTime: "12-24 hours",
    location: "Hanoi, Vietnam",
    terms: "Same-day delivery for orders before 10 AM. 100% freshness guaranteed.",
    images: ["/placeholder-eggs.jpg"],
    createdAt: "2024-10-17T06:00:00Z",
    active: true,
  },
  {
    id: "ad_4",
    seller: mockUsers[3],
    industry: "Textiles",
    product: "Premium Cotton Fabric - Bulk",
    description: "100% pure cotton fabric, various colors available. Perfect for garment manufacturing.",
    price: 4.5,
    priceUnit: "meter",
    minOrder: 50,
    maxOrder: 2000,
    availableStock: 5000,
    paymentMethods: ["Bank Transfer", "PayPal"],
    shippingTime: "5-7 business days",
    location: "Mumbai, India",
    terms: "Bulk pricing available. Minimum order 50 meters. International shipping extra.",
    images: ["/placeholder-fabric.jpg"],
    createdAt: "2024-10-14T11:45:00Z",
    active: true,
  },
  {
    id: "ad_5",
    seller: mockUsers[0],
    industry: "Agriculture",
    product: "Organic Wheat Grain",
    description: "Premium quality organic wheat, stone-ground ready. Perfect for flour production.",
    price: 1.8,
    priceUnit: "kg",
    minOrder: 200,
    maxOrder: 10000,
    availableStock: 15000,
    paymentMethods: ["Bank Transfer", "USDT (TRC-20)"],
    shippingTime: "48-72 hours",
    location: "Bangkok, Thailand",
    terms: "Certified organic. Bulk discounts for orders over 5000kg.",
    images: ["/placeholder-wheat.jpg"],
    createdAt: "2024-10-13T09:15:00Z",
    active: true,
  },
  {
    id: "ad_6",
    seller: mockUsers[1],
    industry: "Electronics",
    product: "Laptop Components - RAM & SSD",
    description: "High-quality laptop upgrades. DDR4 RAM and NVMe SSDs. Tested and guaranteed.",
    price: 45,
    priceUnit: "piece",
    minOrder: 5,
    maxOrder: 100,
    availableStock: 300,
    paymentMethods: ["Bank Transfer", "Crypto (ETH)", "PayPal"],
    shippingTime: "2-4 business days",
    location: "Singapore",
    terms: "1-year warranty on all components. Technical support included.",
    images: ["/placeholder-components.jpg"],
    createdAt: "2024-10-16T16:30:00Z",
    active: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: "order_1",
    advertisement: mockAdvertisements[0],
    buyer: mockUsers[1],
    seller: mockUsers[0],
    quantity: 500,
    totalPrice: 1250,
    paymentMethod: "Bank Transfer",
    status: "payment_confirmed",
    createdAt: "2024-10-17T10:00:00Z",
    paidAt: "2024-10-17T10:15:00Z",
    paymentTimer: 0,
    timeline: [
      { status: "pending_payment", timestamp: "2024-10-17T10:00:00Z" },
      { status: "payment_sent", timestamp: "2024-10-17T10:15:00Z", note: "Bank transfer completed" },
      { status: "payment_confirmed", timestamp: "2024-10-17T10:30:00Z", note: "Payment verified by seller" },
    ],
  },
];

export const mockReviews: Review[] = [
  {
    id: "review_1",
    orderId: "order_completed_1",
    reviewer: mockUsers[1],
    reviewee: mockUsers[0],
    rating: 5,
    comment: "Excellent quality rice, fast shipping. Highly recommended!",
    timestamp: "2024-10-10T14:20:00Z",
  },
  {
    id: "review_2",
    orderId: "order_completed_2",
    reviewer: mockUsers[2],
    reviewee: mockUsers[0],
    rating: 5,
    comment: "Best supplier I've worked with. Very professional.",
    timestamp: "2024-10-08T09:45:00Z",
  },
];
